repos:
  - repo: local
    hooks:
      - id: remove-pycaches
        name: remove-pycaches
        entry: bash -c 'find . -type d -name "__pycache__" -print0 | xargs -0 rm -rf'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

      - id: pytest
        name: pytest
        entry: pytest -q
        language: python
        additional_dependencies: [pytest]
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        name: ruff
        args: ["--fix"]
        files: '\.py$'

exclude: '^(?:\.pre-commit|\.precommit|\.github|.*__pycache__.*|\.venv|venv|env)/'