repos:
  - repo: local
    hooks:
      - id: remove-pycaches
        name: remove-pycaches
        entry: bash -c 'find . -type d -name "__pycache__" -print0 | xargs -0 rm -rf'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

      - id: pytest
        name: pytest
        entry: ./.pre-commit-install-deps.sh
        language: python
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

      - id: helm-template
        name: helm-template
        entry: bash -c 'helm template ./helm --debug'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

      - id: helm-template-generate-kyverno-policy
        name: helm-template-generate-kyverno-policy
        entry: bash -c 'helm template automatic-zone-placement helm/ --show-only templates/kyverno_clusterpolicy.yaml > resources/kyverno_clusterpolicy.yaml'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

      - id: kyverno-test
        name: kyverno-test
        entry: bash -c 'kyverno test tests -v9'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit, pre-push]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        name: ruff
        args: ["--fix"]
        files: '\.py$'

exclude: '^(?:\.pre-commit|\.precommit|\.github|.*__pycache__.*|\.venv|venv|env)/'