apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "automatic-zone-placement.fullname" . }}-subnets
  labels:
    {{- include "automatic-zone-placement.labels" . | nindent 4 }}
data:
  subnets.json: {{ .Values.subnets | quote }}
