name: Test

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.14'
  HELM_VERSION: 'v3.19.4'
  KYVERNO_VERSION: 'v1.16.1'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Show Python version
        run: |
          python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Show Pytest version
        run: |
          pytest --version
      - name: Run tests
        run: |
          pytest -v
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}
      - name: Show Helm version
        run: |
          helm version
      - name: Test Helm chart
        run: |
          helm template ./helm --debug
      - name: Test Helm chart with default values
        run: |
          helm template ./helm --debug
      - name: Install Kyverno CLI
        run: |
          curl -LO https://github.com/kyverno/kyverno/releases/download/${{ env.KYVERNO_VERSION }}/kyverno-cli_${{ env.KYVERNO_VERSION }}_linux_x86_64.tar.gz
          tar -xvf kyverno-cli_${{ env.KYVERNO_VERSION }}_linux_x86_64.tar.gz
          sudo mv kyverno /usr/local/bin/
          
      - name: Show Kyverno version
        run: |
          kyverno version
      - name: Generate Kyverno Policy
        run: |
          mkdir -p resources
          helm template automatic-zone-placement helm/ --show-only templates/kyverno_clusterpolicy.yaml > resources/kyverno_clusterpolicy.yaml

      - name: Run Kyverno Tests
        run: |
          kyverno test tests -v9

      - name: Build image
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: local/automatic-zone-placement:latest

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'local/automatic-zone-placement:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
